// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTL9myvr-GVpy7rqc_Rry20MyJNF-9yPA',
    appId: '1:443155913502:web:5eb683683fefa878ae470f',
    messagingSenderId: '443155913502',
    projectId: 'foodme-backend',
    authDomain: 'foodme-backend.firebaseapp.com',
    storageBucket: 'foodme-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-fgO5Li23LpD2u1IJR89J2UtU3_5dWY',
    appId: '1:443155913502:android:61d20cd8c8ea095dae470f',
    messagingSenderId: '443155913502',
    projectId: 'foodme-backend',
    storageBucket: 'foodme-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMqEguoxOfkI9VFQUrzeSJNdJLfFNSnmY',
    appId: '1:443155913502:ios:bd0bab2f0512316cae470f',
    messagingSenderId: '443155913502',
    projectId: 'foodme-backend',
    storageBucket: 'foodme-backend.appspot.com',
    iosClientId: '443155913502-ijsirit1uv3f3h411hhbli7t7m6u41p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodmeBackend',
  );
}
